select * from Sales

-- Count the number of transactions and customers.
select count(transaction_id)
from sale;

select count(customer_id)
from sales;

-- Find the total revenue generated.
select sum(quantity*price) AS total_revenue
from sales;

select product_id,product_name, category, sum(quantity) AS total_quantity_sold
from sales
group by product_id, product_name, category
order by total_quantity_sold desc
limit 5;

-- Identify the top-selling products and categories.
select category, sum(quantity) AS total_quantity_sold
from sales
group by category
order by total_quantity_sold desc
limit 5;

-- Calculate the average price and quantity of products sold.
select  
		avg(price) as average_price,
		avg(quantity) as avearage_quantity
from sales;

-- Time-based Analysis:
#Analyze Monthly Sales
select 
	date_format(transaction_date, '%Y-%m') as month,
	sum(quantity * price) as total_sales
from sales
group by month
order by month;

#Analyze Quarterly Sales
select
	concat(year(transaction_date), '-', quarter(transaction_date)) As quarter,
    sum(quantity * price) as total_sales
from sales
group by quarter
order by quarter;

#Analyze sales trends over time (monthly or quarterly sales).
select
	date_format(transaction_date, '%Y-%m') as month,
    sum(quantity*price) as total_sales
from sales
group by month
order by total_sales desc;

-- Identify the top-spending customers.
SELECT
    customer_id,
    SUM(quantity * price) AS total_spent
FROM sales
GROUP BY customer_id
ORDER BY total_spent DESC;

-- Calculate the average number of transactions per customer.
SELECT
    AVG(transaction_count) AS average_transactions_per_customer
FROM
    (SELECT
        customer_id,
        COUNT(transaction_id) AS transaction_count
    FROM sales
    GROUP BY customer_id) AS customer_transaction_count;

-- Analyze sales by country.
select
	country,
    sum(quantity * price) as total_sales
from sales
group by country
order by total_sales desc;

-- Calculate the revenue and total number of transactions for each country.
select
	country,
    count(transaction_id) as total_transacction,
    sum(quantity * price) as total_revenue
from  sales
group by country;

-- Visualize the sales distribution on a map.
select
	country,
    sum(quantity * price) as total_sales,
    latitude,
    longitude
from sales
group by country, latitude, longitude;

-- Identify the most popular product categories.
select
	category,
    sum(quantity) as total_quantity_sold
from sales
group by category
order by total_quantity_sold desc;

-- Calculate the revenue generated by each category.
select 
	category,
    sum(quantity * price) as total_revenue
from sales
group by category;

-- Determine the percentage of total revenue contributed by each category.
select
	sum(quantity * price) as category_revenue,
	SUM(quantity * price) / (SELECT SUM(quantity * price) FROM sales) * 100 AS revenue_percentage
  from sales
  group by category;
  
-- Check the stock levels for each product.
select
	product_id,
    product_name,
    quantity
from sales;

-- entify products that are running low on inventory.
select
	product_id,
    product_name
    quantity
from sales
where quantity<10;

